name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Booking-Referrals-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    enable_status_monitoring: false
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-tests.yml
      -   environment: internal-dev-sandbox
          proxy_path: sandbox
          enable_status_monitoring: true
          post_deploy:
              -   template: ./templates/run-tests.yml
      - environment: internal-qa
        post_deploy:
          - template: ./templates/run-tests.yml
      - environment: internal-qa-sandbox
        proxy_path: sandbox
        enable_status_monitoring: true
        post_deploy:
          - template: ./templates/run-tests.yml
    # make_spec_visible is false for sandbox environment
    # (App subscription make sense for most sandbox implementations)
      - environment: sandbox
        proxy_path: sandbox
        enable_status_monitoring: true
        post_deploy:
          - template: ./templates/run-tests.yml
      - environment: int
        depends_on:
          - internal_qa
          - internal_qa_sandbox
        post_deploy:
          - template: ./templates/run-tests.yml
      - environment: prod
        enable_status_monitoring: true
        depends_on:
          - int
          - sandbox
