openapi: 3.0.0
info:
  description: |
    new spec
  version: 1.0.8
  title: Booking and Referral API
contact:
  name: API Support
  url: http://www.example.com/support
  email: support@example.com
license:
  name: Apache 2.0
  url: https://www.apache.org/licenses/LICENSE-2.0.html
version: 1.0.1
